### PR TITLE
Update docker-compose.mkdocs.yaml

### LINKED ISSUE #1: Docs folder and config file in root of project
Thanks for making this. I'd like to recommend it in https://github.com/ddev/ddev-drupal-contrib. But the [drupal.org Gitlab CI implementation of mkdocs-material ](https://git.drupalcode.org/project/gitlab_templates/-/blob/main/includes/include.drupalci.main.yml?ref_type=heads#L347-362)expects doc files to be in /docs dir, not mkdocs/docs. And it expects mkdocs.yml to be in project root. Would it be possible to make these changes?

### PR DESCRIPTION
**Pull request by bhanu951**
Resolves https://github.com/nireneko/ddev-mkdocs/issues/1

### CODE REVIEW

**Review by rfay — COMMENTED** [review]
I didn't test it, but it looks right to me.

**Comment by nireneko** [comment]
@bhanu951 don't forget the install.yml file, creates the folder and the mkdocs.yml file.
Could you check it please?

**Comment by bhanu951** [comment]
@nireneko changes made please review.

**Comment by nireneko** [comment]
Checked on local and works, but in existing projects mkdocs.yml and docs folder must be moved out of mkdocs folder, if not, the project won't start.

I'm going to merge this and put one note in the release notes.

Thanks :)

**Pull request merged**
